openapi: 3.0.0
info:
  version: "1.0.0"
  title: "OPM"

paths:
  /user/signup:
    post:
      summary: "새로운 유저 회원가입"
      tags:
        - User
      consumes:
        - application/json
      parameters:
        - in: body
          schema:
            type: object
            properties:
              uEmail: 
                type: string
              uPassword:
                type: string
              uFirstName:
                type: string
              uLastName:
                type: string
      