openapi: 3.0.0
info:
  version: "1.0.0"
  title: "OPM"

servers:
  - url: http://49.50.166.140:8080/

paths:
  /user/all:
    get:
      summary: "유저 정보 불러오기"
      tags:
        - User
      response:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
