version: "3.8"

services:
  nginx_proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./apps/front/dist:/usr/share/nginx/html
    container_name: nginx_proxy
    # restart: "always"

  # web:
  #   build:
  #     context: ./../front/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   container_name: web
  #   # restart: "always"

  # server:
  #   build:
  #     context: ./../back/
  #     dockerfile: Dockerfile
  #   # stdin_open: true
  #   # tty: true
  #   ports:
  #     - 8080:8080
  #   # volumes:
  #   #   - '/app/node_modules'
  #   container_name: server
  #   # restart: "always"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb
    restart: on-failure

  # turbo:
  #   container_name: turbo
  #   links:
  #     - mongodb
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - "3000:3000"
  #     - "8080:8080"
  #   volumes:
  #     - ./:/apps/
  #     - /apps/node_modules/
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=1234
  #   restart: on-failure

# networks:
#   turbo-network:
#     driver: bridge